# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: drmoskit
  # This sets the pull policy for images.
  tag: ""
  arch: amd64
# Додатково визначте секцію для токену TELE_TOKEN
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
httpRoute:
  enabled: false
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
serviceAccount:
  create: true
  name: "kbot-helm"
service:
  type: ClusterIP
  port: 80
teleTokenSecret:
  name: "kbot"
  key: "token"
  env: "TELE_TOKEN"
ingress:
  enabled: false
image:
  repository: ghcr.io/drmoskit/kbot
  tag: ""
  arch: amd64
